trigger:
 branches:
   include:
     - master
stages:
  - stage: Build_stage
    displayName: Build
    jobs:
      - job:
        displayName: web app
        pool:
          vmImage: windows-latest
        variables:
          BuildConfiguration: Release
        steps:
        - task: DotNetCoreCLI@2
          displayName: restore
          inputs:
            command: 'restore'
            projects: '**/WebApp.csproj'
            feedsToUse: 'select'
            
        - task: DotNetCoreCLI@2
          displayName: build
          inputs:
            command: 'build'
            projects: '**/WebApp.csproj'
            arguments: '--configuration $(BuildConfiguration)'
          
        - task: DotNetCoreCLI@2
          displayName: publish
          inputs:
            command: 'publish'
            publishWebProjects: true
            arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
            zipAfterPublish: true
          
        - task: PublishBuildArtifacts@1
          displayName: PublishBuildArtifacts
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'drop'
            publishLocation: Container
          
        - task: DownloadBuildArtifacts@1
          inputs:
            buildType: 'current'
            downloadType: 'single'
            artifactName: 'drop'
            downloadPath: '$(System.ArtifactsDirectory)'
  - stage:
    displayName: deploy
    pool:
         vmImage: ubuntu-latest
    jobs:
      - job: 
      - deployment: 
        environment:
           name: dotnetvm
           
        strategy:
         runOnce:
           deploy:
             steps:
               - download: current
                 name: DownloadBuildArtifacts
                 artifact: drop
                     
               - task: IISWebAppManagementOnMachineGroup@0
                 inputs:
                   EnableIIS: true
                   IISDeploymentType: 'IISWebsite'
                   ActionIISWebsite: 'CreateOrUpdateWebsite'
                   WebsiteName: 'WebApp'
                   WebsitePhysicalPath: '%SystemDrive%\inetpub\wwwroot'
                   WebsitePhysicalPathAuth: 'WebsiteUserPassThrough' 

               - task: IISWebAppDeploymentOnMachineGroup@0
                 inputs:
                   WebSiteName: 'WebApp'
                   Package: 'D:\a\1'
               - task: IISWebAppManagementOnMachineGroup@0
                 inputs:
                   EnableIIS: true
                   IISDeploymentType: 'IISWebsite'
                   ActionIISWebsite: 'StartWebsite'
                   StartStopWebsiteName: 'WebApp'